pool_type: "attn.d2.nh8.glusw"
arch: "vit_base_p16_fz.v2.t2"
hidden_dim: 512
image_feature_dim: 512
mlp_adapter_spec: "v0-2.t0"
resolution: [160, 256]

ckpt:
  path: "/home/ubuntu/MineAgentFinal/weights/attn.pth"  # filled by users
  checksum: "b5ece9198337cfd117a3bfbd921e56da"